version: "3.8"
services:
  backend:
    image: "akayehia/spring-react-fullstack:17.5.2023.17.13.34"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev