version: "3.8"
services:
  backend:
    image: "akayehia/spring-react-fullstack:22.7.2023.18.34.27"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev