version: "3.8"
services:
  backend:
    image: "akayehia/spring-react-fullstack:17.7.2023.15.13.30"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev