version: "3.8"
services:
  backend:
    image: "akayehia/spring-react-fullstack:18.5.2023.13.25.54"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev